services:
  - type: worker
    name: telegram-video-to-mp3-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 1
    plan: free # Ücretsiz plan
    buildCommand: "" # Boş bırakıyoruz çünkü Dockerfile kullanıyoruz
    startCommand: "python bot.py" 